Error when None
Using `./OtherMSBinaries/Remote.yml` as an example, when running a command like `/gtfoblookup.py lolbas search -c exec remote` will give an error:

Traceback (most recent call last):

  [snip]
  File "./gtfoblookup.py", line 470, in extractYmlLolbas
    line += cmd[attr]
TypeError: can only concatenate str (not "NoneType") to str


This is because the yml file has and empty value (OperatingSystem):

    Category: Execute
    Privileges: User
    MitreID: T1127
    OperatingSystem: